/*
 * Copyright 2018 Diffblue Limited
 *
 * Diffblue Limited licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package spark.utils;

import org.junit.Assert;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import spark.utils.ClassUtils;

public class ClassUtilsTest {

  @Rule public ExpectedException thrown = ExpectedException.none();

  /* testedClasses: ClassUtils */

  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   *  - conditional line 254 branch to line 255
   */

  @Test
  public void classPackageAsResourcePathInputNullOutputNotNull() {

    // Arrange
    final Class clazz = null;

    // Act
    final String retval = ClassUtils.classPackageAsResourcePath(clazz);

    // Assert result
    Assert.assertEquals("", retval);
  }

  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   *  - conditional line 231 branch to line 231
   *  - conditional line 231 branch to line 235
   */

  @Test
  public void resolvePrimitiveClassNameInputNotNullOutputNull() {

    // Arrange
    final String name = "AAAAAAAAAA";

    // Act
    final Class retval = ClassUtils.resolvePrimitiveClassName(name);

    // Assert result
    Assert.assertNull(retval);
  }

  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   *  - conditional line 231 branch to line 235
   */

  @Test
  public void resolvePrimitiveClassNameInputNullOutputNull() {

    // Arrange
    final String name = null;

    // Act
    final Class retval = ClassUtils.resolvePrimitiveClassName(name);

    // Assert result
    Assert.assertNull(retval);
  }
}
